name: Build LaTeX Docs

on:
  push:
    paths:
      - '002_documentacao/index.tex'

jobs:
  build-latex-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Install TeX Live
      run: |
        sudo apt update -y
        sudo apt install texlive-full -y
    - name: Compile LaTeX Docs
      run: pdflatex \\nonstopmode\\input 002_documentacao/index.tex
    - name: Upload Artifact
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
      with:
        name: documentacao-grupo-1
        path: index.pdf
